### ISSUE TITLE
Wrong offsets being reported by Sherlock

### ISSUE THREAD

**Issue by mnicholl** [lsst-uk/lasair#53] opened 2019-12-06 17:04 UTC
I'm finding cases where multiple transients, with near-consecutive ZTF names (looks like they were discovered in the same image based on identical historic detection limits) and associated with the same galaxy by Sherlock, have identical offsets from the nearest galaxy even though they have different coordinates.

It looks like the north and east separations are being computed probably correctly, but then something goes wrong in combining this into an overall separation.

I've made a public query called Sherlock-bug that demonstrates the issue. You can see that all objects returned have the same separationArcsec and physical_separation_kpc

**Comment by genghisken** [comment] 2019-12-06 17:52
Hi Matt.  This looks like a generic Sherlock issue rather than a specific Lasair one.  Can you raise an issue (cut/paste) on Dave's Sherlock page?

https://github.com/thespacedoctor/sherlock/issues

**Comment by thespacedoctor** [comment] 2019-12-10 11:42
There seems to be a bug in Sherlock where multiple transients are found in the same ZTF image and are associated with the same host galaxy. Although the transient coordinates the host-transient N-E separations reported are different, the combined angular- and physical-separations reported are 1. wrong, and 2. exactly the same!

Here's a modified version of the query Matt created:

```sql
SELECT 
    objectId, jdmin, catalogue_object_id, northSeparationArcsec, separationArcsec, eastSeparationArcsec, physical_separation_kpc, direct_distance_scale, direct_distance
FROM
    objects,
    sherlock_crossmatches
WHERE
    objects.objectId = objects.objectId
        AND objects.primaryId = sherlock_crossmatches.transient_object_id
        AND objects.jdmax > JDNOW() - 180.00000
        AND objects.sherlock_classification = 'SN'
        AND sherlock_crossmatches.direct_distance < 200
        AND sherlock_crossmatches.rank = 1
        AND objects.jdmin > JDNOW() - 180
        AND objects.ncandgp > 0
        AND objects.ncand - objects.ncandgp < 2
        AND sherlock_crossmatches.catalogue_object_id = 'UGC04171';
```

And the results:

![](https://live.staticflickr.com/65535/49197980916_3b31e52f43_o.png)

I notice that the sherlock version on `lasair-node0` is >1 year out of date! 

First check is to clear out the classifications for these 7 ZTF sources above, rerun the installed version of sherlock (v1.6.3) and see if I get the same results. And the answer is .. NO. These are the results I get after rerunning sherlock (ran twice with consistent results).

![](https://live.staticflickr.com/65535/49197750538_22b3c7490d_o.png)

So **the Sherlock code is NOT the source of this issue**. The issue is the in the way Sherlock is being run.

**ISSUE NUMBER 1**

The following queries in the Sherlock settings file have different `jdmax` limits injected. Why???? In the 'transient count' it is set to 3rd Dec 2019 and in the 'transient query' it is set to 27th Oct 2019:

```yaml
transient count: "select count(*) from objects where jdmax>2458821 and sherlock_classification is null"
transient query: "select primaryId as 'id', objectId as 'alt_id', ramean 'ra', decmean 'dec', objectId 'name', sherlock_classification as 'object_classification' from objects where jdmax>2458784 and sherlock_classification is null"
```

Sherlock cannot correctly do bookkeeping with these oddly incompatible queries. Why do we have a date limit? If the issue is with the number of sources needing classification then please reimplement the ncand>2 limit.

These arbitrary date limits prevent all objects from being classified and therefore any queries users run against sherlock classifications (e.g. Matt's queries) will be opaquely incomplete.

**ISSUE NUMBER 2**

A 30 minute timeout has been placed on Sherlock after which the process is killed!

<https://github.com/lsst-uk/lasair/blob/master/src/post_ingest/run_sherlock.py>

Ungracefully killing any process that works with databases is obviously going to leave the data in an incomplete and unreliable state.

**Comment by thespacedoctor** [comment] 2020-04-06 11:47
I see now that issue 1 has been fixed - thanks Roy.

Still a concern remaining about issue 2 above.

**Comment by thespacedoctor** [comment] 2020-05-13 08:15
issues have been fixed now

**Closed by thespacedoctor** 2020-05-13 08:15 UTC
